version: '3'

services:

  h2:
    image: oscarfonts/h2:latest
    container_name: h2
    ports:
      - "9092:9092"  # Exposes H2 port
    volumes:
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql  # Initialization script
    networks:
      - app-network

  #  redis:
  #    image: redis:latest
  #    container_name: redis
  #    ports:
  #    - "6379:6379"  # Exposes Redis port
  #    networks:
  #    - app-network
  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    #      - SPRING_DATA_MONGODB_URI= mongodb://mongo:27017
    ports:
      - "8080:8080"
    depends_on:
      - h2
    networks:
      - app-network


networks:
  app-network:
    driver: bridge