spring:
  application:
    name: backend-mortgage-system
  datasource:
    url: jdbc:h2:mem:mortgage-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: h2

appUserName: user
password: password


#cache:
#  ttl: 3 # Time-to-live for cache entries 3 days

management:
  endpoints:
    web:
      exposure:
        include: health,info
